version: "3"
services:
  test-base:
    image: prismagraphql/build:test
    environment:
      SERVER_ROOT: /root/build
      COMMIT_SHA: "ci_test_binary"
      RUST_BACKTRACE: "1"
      IS_BUILDKITE: "1"
      RUST_LOG_FORMAT: "devel"
      LOG_LEVEL: "error"
    volumes:
      - .:/root/build
    working_dir: /root/build/
    networks:
      - engine-tests

  test-db-postgres-9:
    image: postgres:9
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
    ports:
      - "5431:5432"
    networks:
      - engine-tests

  test-db-postgres-10:
    image: postgres:10
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
    ports:
      - "5432:5432"
    networks:
      - engine-tests

  test-db-postgres-11:
    image: postgres:11
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
    ports:
      - "5433:5432"
    networks:
      - engine-tests

  test-db-postgres-12:
    image: postgres:12
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
    ports:
      - "5434:5432"
    networks:
      - engine-tests

  test-db-postgres-13:
    image: postgres:13
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
    ports:
      - "5435:5432"
    networks:
      - engine-tests

  test-db-pgbouncer:
    image: brainsam/pgbouncer:latest
    restart: always
    environment:
      DB_HOST: "test-db-postgres-11"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "prisma"
      POOL_MODE: "transaction"
      MAX_CLIENT_CONN: "1000"
      SERVER_RESET_QUERY_ALWAYS: "1"
      SERVER_RESET_QUERY: "DEALLOCATE ALL"
    networks:
      - engine-tests
    ports:
      - "6432:6432"

  test-db-mysql-5-6:
    image: mysql:5.6.50
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3309:3306"
    networks:
      - engine-tests

  test-db-mysql-5-7:
    image: mysql:5.7.32
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3306:3306"
    networks:
      - engine-tests

  test-db-mysql-8-0:
    image: mysql:8.0.22
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3307:3306"
    networks:
      - engine-tests

  test-db-mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3308:3306"
    networks:
      - engine-tests

  test-db-mssql-2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"
    networks:
      - engine-tests

  test-db-mssql-2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1434:1433"
    networks:
      - engine-tests

networks:
  engine-tests:
